### ISSUE TITLE
Does not work without FontAwesome

### ISSUE THREAD

**Issue by amahdy** [snyholm/indeterminatecheckbox#2]
I'm using Vaadin font icons so it didn't work.
Here is a hack to work around this:

```CSS
	.v-checkbox.v-indeterminate-checkbox > input ~ label:after {
		font-family: FontAwesome;
	}
```
